'use strict';

/**
 * Schema definition for `category`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.150Z
 */
module.exports = ({ defineModel }) => defineModel('category', {
  fields: {
    category_id: 'string:36 pk',
    category_code: 'string:20 notnull unique',
    category_name: 'string:100 notnull',
    description: 'string:500',
    is_active: 'boolean default:true',
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  indexes: [
    'is_active'
  ]
});
