'use strict';

/**
 * Schema definition for `city`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.151Z
 */
module.exports = ({ defineModel }) => defineModel('city', {
  fields: {
    city_id: 'string:36 pk',
    city_code: 'string:20 notnull unique',
    city_name: 'string:100 notnull',
    country: "string:100 notnull default:'INDONESIA'",
    is_active: 'boolean default:true'
  },

  indexes: [
    'country',
    'is_active'
  ]
});
