'use strict';

/**
 * Schema definition for `customer`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.152Z
 */
module.exports = ({ defineModel }) => defineModel('customer', {
  fields: {
    customer_id: 'string:36 pk',
    customer_code: 'string:20 notnull unique',
    customer_name: 'string:255 notnull',
    contact_person: 'string:100',
    phone: 'string:20',
    email: 'string:100',
    address: 'text',
    city: 'string:100 notnull',
    country: "string:100 notnull default:'INDONESIA'",
    register_date: 'date',
    amount_receivable: 'decimal:15,2 default:0',
    is_active: 'boolean default:true',
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  indexes: [
    'is_active'
  ]
});
