'use strict';

/**
 * Schema definition for `item_product`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.152Z
 */
module.exports = ({ defineModel }) => defineModel('item_product', {
  fields: {
    item_product_id: 'string:36 pk',
    product_code: 'string:20 notnull unique',
    sku: 'string:20 notnull unique',
    product_name: 'string:100 notnull',
    category_id: 'string:36 notnull',
    brand: 'string:50',
    description: 'string:500',
    purchase_price: 'decimal:15,2 notnull default:0',
    selling_price: 'decimal:15,2 notnull default:0',
    stock: 'decimal:15,0 notnull default:0',
    min_stock: 'decimal:15,0 default:0',
    uom: "string:10 default:'pcs'",
    weight: 'decimal:10,2 default:0',
    is_active: 'boolean default:true',
    show_in_store: 'boolean default:true',
    barcode: 'string:20',
    shelf_location: 'string:20',
    notes: 'string:500',
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  indexes: [
    'barcode',
    'category_id',
    'is_active'
  ],

  relations: {
    category: {
      type: 'belongsTo',
      target: 'category',
      localKey: 'category_id',
      references: 'category_id',
      onDelete: 'restrict',
      onUpdate: 'restrict'
    }
  }
});
