'use strict';

/**
 * Schema definition for `stock_outbound_item`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.153Z
 */
module.exports = ({ defineModel }) => defineModel('stock_outbound_item', {
  fields: {
    stock_outbound_item_id: 'string:36 pk',
    stock_outbound_id: 'string:36 notnull',
    line_number: 'integer notnull',
    item_product_id: 'string:36 notnull',
    qty_shipped: 'decimal:15,0 notnull default:0',
    uom: "string:10 default:'pcs'",
    unit_price: 'decimal:15,2 default:0',
    total_amount: 'decimal:15,2 default:0',
    notes: 'text',
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  uniques: [
    ['stock_outbound_id', 'line_number']
  ],

  indexes: [
    'stock_outbound_id',
    ['stock_outbound_id', 'item_product_id'],
    'item_product_id'
  ],

  relations: {
    stock_outbound: {
      type: 'belongsTo',
      target: 'stock_outbound',
      localKey: 'stock_outbound_id',
      references: 'stock_outbound_id',
      onDelete: 'cascade',
      onUpdate: 'restrict'
    },
    item_product: {
      type: 'belongsTo',
      target: 'item_product',
      localKey: 'item_product_id',
      references: 'item_product_id',
      onDelete: 'restrict',
      onUpdate: 'restrict'
    }
  }
});
