'use strict';

/**
 * Schema definition for `stock_inbound`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.153Z
 */
module.exports = ({ defineModel }) => defineModel('stock_inbound', {
  fields: {
    stock_inbound_id: 'string:36 pk',
    inbound_number: 'string:50 notnull unique',
    inbound_date: 'date notnull default:current_date',
    warehouse_id: 'string:36 notnull',
    supplier_id: 'string:36',
    reference_number: 'string:50',
    notes: 'text',
    total_items: 'integer default:0',
    total_qty: 'decimal:15,0 default:0',
    total_amount: 'decimal:15,2 default:0',
    status: "string:20 default:'draft'",
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  indexes: [
    'inbound_date',
    'status',
    'supplier_id',
    'warehouse_id'
  ],

  relations: {
    supplier: {
      type: 'belongsTo',
      target: 'supplier',
      localKey: 'supplier_id',
      references: 'supplier_id',
      onDelete: 'setNull',
      onUpdate: 'restrict'
    },
    warehouse: {
      type: 'belongsTo',
      target: 'warehouse',
      localKey: 'warehouse_id',
      references: 'warehouse_id',
      onDelete: 'restrict',
      onUpdate: 'restrict'
    }
  }
});
