'use strict';

/**
 * Schema definition for `stock_beginning_balance`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.152Z
 */
module.exports = ({ defineModel }) => defineModel('stock_beginning_balance', {
  fields: {
    stock_beginning_balance_id: 'string:36 pk',
    item_product_id: 'string:36 notnull',
    warehouse_id: 'string:36 notnull',
    period_date: 'date notnull',
    qty_beginning: 'decimal:15,0 notnull default:0',
    notes: 'text',
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  uniques: [
    ['item_product_id', 'warehouse_id', 'period_date']
  ],

  indexes: [
    'item_product_id',
    ['item_product_id', 'warehouse_id'],
    'period_date',
    'warehouse_id'
  ],

  relations: {
    item_product: {
      type: 'belongsTo',
      target: 'item_product',
      localKey: 'item_product_id',
      references: 'item_product_id',
      onDelete: 'restrict',
      onUpdate: 'restrict'
    },
    warehouse: {
      type: 'belongsTo',
      target: 'warehouse',
      localKey: 'warehouse_id',
      references: 'warehouse_id',
      onDelete: 'restrict',
      onUpdate: 'restrict'
    }
  }
});
