'use strict';

/**
 * Schema definition for `warehouse`
 *
 * Generated by: npx restforge schema introspect
 * Generated at: 2026-06-03T03:09:33.153Z
 */
module.exports = ({ defineModel }) => defineModel('warehouse', {
  fields: {
    warehouse_id: 'string:36 pk',
    warehouse_code: 'string:20 notnull unique',
    warehouse_name: 'string:255 notnull',
    warehouse_type: 'string:50',
    address: 'text',
    city: 'string:100',
    capacity: 'decimal:15,2',
    is_active: 'boolean default:true',
    created_at: 'timestamp',
    created_by: 'string:70',
    updated_at: 'timestamp',
    updated_by: 'string:70'
  },

  indexes: [
    'is_active'
  ]
});
